/*
 * web_ui.c
 *
 * The complete browser interface, embedded as one string.
 *
 * Design constraints:
 *   - fully self contained: no CDN, no external fonts, works
 *     on an isolated LAN with no internet access
 *   - WebRTC only: <video> element fed by RTCPeerConnection,
 *     with a live statistics dashboard drawn from getStats()
 *   - single quotes only inside the markup so the C string
 *     needs no escaped quotes
 */
const char *web_ui_html =
"<!doctype html>"
"<html lang='en'>"
"<head>"
"<meta charset='utf-8'>"
"<meta name='viewport' content='width=device-width,initial-scale=1'>"
"<title>camstream</title>"
"<style>"
":root{"
"--bg:#0b1020;"
"--card:rgba(255,255,255,.045);"
"--card2:rgba(255,255,255,.07);"
"--line:rgba(255,255,255,.09);"
"--text:#e8ecf8;"
"--dim:#93a0bd;"
"--teal:#2dd4bf;"
"--blue:#60a5fa;"
"--violet:#a78bfa;"
"--red:#f87171;"
"--amber:#fbbf24;"
"--green:#34d399;"
"--mono:ui-monospace,'Cascadia Mono',Menlo,Consolas,monospace;"
"}"
"*{box-sizing:border-box;margin:0;padding:0}"
"html,body{height:100%}"
"body{"
"font-family:system-ui,-apple-system,'Segoe UI',Roboto,sans-serif;"
"background:"
"radial-gradient(1200px 700px at 85% -10%,rgba(96,165,250,.16),transparent 60%),"
"radial-gradient(1000px 600px at -10% 110%,rgba(167,139,250,.14),transparent 55%),"
"var(--bg);"
"color:var(--text);"
"min-height:100%;"
"}"
".wrap{max-width:1240px;margin:0 auto;padding:20px 20px 40px}"
"header{display:flex;align-items:center;gap:14px;flex-wrap:wrap;padding:6px 2px 18px}"
".logo{width:38px;height:38px;border-radius:12px;"
"background:linear-gradient(135deg,var(--teal),var(--blue) 55%,var(--violet));"
"display:grid;place-items:center;box-shadow:0 6px 24px rgba(96,165,250,.35)}"
".logo svg{width:18px;height:18px;fill:#0b1020}"
"h1{font-size:20px;font-weight:650;letter-spacing:.2px}"
".sub{color:var(--dim);font-size:12.5px;margin-top:2px}"
".pill{font-size:11px;letter-spacing:.6px;text-transform:uppercase;"
"padding:4px 10px;border-radius:999px;border:1px solid var(--line);"
"background:var(--card);color:var(--dim)}"
".pill.ok{color:var(--green);border-color:rgba(52,211,153,.35)}"
".pill.bad{color:var(--red);border-color:rgba(248,113,113,.35)}"
".pill.live{color:#fff;background:linear-gradient(135deg,#ef4444,#f97316);border:0}"
".dot{display:inline-block;width:7px;height:7px;border-radius:50%;"
"background:currentColor;margin-right:6px;animation:pulse 1.4s infinite}"
"@keyframes pulse{0%,100%{opacity:1}50%{opacity:.25}}"
".grid{display:grid;grid-template-columns:minmax(0,2.1fr) minmax(300px,1fr);gap:18px}"
"@media(max-width:980px){.grid{grid-template-columns:1fr}}"
".card{background:var(--card);border:1px solid var(--line);border-radius:18px;"
"backdrop-filter:blur(10px);padding:16px}"
".card h2{font-size:13px;font-weight:600;letter-spacing:1.1px;text-transform:uppercase;"
"color:var(--dim);margin-bottom:12px;display:flex;align-items:center;gap:8px}"
".stage{position:relative;background:#05070f;border-radius:18px;overflow:hidden;"
"border:1px solid var(--line)}"
".stage video{display:block;width:100%;aspect-ratio:4/3;"
"object-fit:contain;background:#000}"
".stage .idle{position:absolute;inset:0;display:grid;place-items:center;"
"text-align:center;color:var(--dim);gap:10px;font-size:14px;padding:24px}"
".stage .idle .big{font-size:44px}"
".overlay{position:absolute;top:12px;left:12px;right:12px;display:flex;"
"justify-content:space-between;gap:10px;pointer-events:none}"
".tag{font-family:var(--mono);font-size:11.5px;padding:5px 9px;border-radius:9px;"
"background:rgba(5,7,15,.72);border:1px solid var(--line);color:#cdd7ee}"
".controls{display:flex;gap:10px;flex-wrap:wrap;padding:14px 16px 4px}"
"button{font:inherit;font-size:13.5px;font-weight:600;color:var(--text);"
"background:var(--card2);border:1px solid var(--line);border-radius:12px;"
"padding:10px 16px;cursor:pointer;transition:transform .12s ease,box-shadow .2s ease}"
"button:hover{transform:translateY(-1px);box-shadow:0 6px 18px rgba(0,0,0,.35)}"
"button:disabled{opacity:.45;cursor:not-allowed;transform:none}"
"button.primary{background:linear-gradient(135deg,var(--teal),var(--blue) 60%,var(--violet));"
"color:#061020;border:0}"
"button.danger{background:linear-gradient(135deg,#f87171,#ef4444);color:#fff;border:0}"
"button.ghost{background:transparent}"
".steps{display:flex;flex-direction:column;gap:8px}"
".step{display:flex;align-items:center;gap:10px;font-size:13px;"
"padding:9px 12px;border-radius:12px;background:var(--card2);border:1px solid var(--line);"
"color:var(--dim);transition:all .25s ease}"
".step .ic{width:20px;height:20px;border-radius:50%;display:grid;place-items:center;"
"font-size:11px;border:1.5px solid var(--line);flex:none;font-family:var(--mono)}"
".step.active{color:var(--text);border-color:rgba(96,165,250,.5)}"
".step.active .ic{border-color:var(--blue);color:var(--blue);animation:pulse 1.1s infinite}"
".step.ok{color:var(--text)}"
".step.ok .ic{border-color:var(--green);background:rgba(52,211,153,.15);color:var(--green)}"
".step.fail{color:var(--red)}"
".step.fail .ic{border-color:var(--red);color:var(--red)}"
".stats{display:grid;grid-template-columns:repeat(3,1fr);gap:10px}"
".stat{background:var(--card2);border:1px solid var(--line);border-radius:14px;"
"padding:10px 12px;min-width:0}"
".stat .v{font-family:var(--mono);font-size:19px;font-weight:600;"
"font-variant-numeric:tabular-nums;white-space:nowrap}"
".stat .l{font-size:10.5px;letter-spacing:.8px;text-transform:uppercase;"
"color:var(--dim);margin-top:3px}"
".spark{width:100%;height:34px;display:block;margin-top:8px;border-radius:8px;"
"background:rgba(0,0,0,.25)}"
".stack{display:flex;flex-direction:column;gap:18px;min-width:0}"
".rowline{display:flex;justify-content:space-between;gap:12px;font-size:13px;"
"padding:7px 0;border-bottom:1px dashed var(--line)}"
".rowline:last-child{border-bottom:0}"
".rowline .k{color:var(--dim)}"
".rowline .v{font-family:var(--mono);font-size:12.5px;text-align:right;word-break:break-all}"
"a.ip{color:var(--blue);text-decoration:none}a.ip:hover{text-decoration:underline}"
".log{font-family:var(--mono);font-size:12px;max-height:220px;overflow:auto;"
"display:flex;flex-direction:column-reverse;gap:3px;color:#b9c4dd}"
".log .t{color:#5a6785;margin-right:8px}"
".log .warn{color:var(--amber)}.log .err{color:var(--red)}.log .ok{color:var(--green)}"
".hint{display:none;font-size:12.5px;line-height:1.55;color:#dbe3f8;"
"background:rgba(251,191,36,.08);border:1px solid rgba(251,191,36,.3);"
"border-radius:12px;padding:10px 12px;margin-top:10px}"
".hint.show{display:block}"
"footer{color:var(--dim);font-size:12px;margin-top:22px;line-height:1.6}"
"table{width:100%;border-collapse:collapse;font-size:12.5px}"
"th,td{text-align:left;padding:6px 8px;border-bottom:1px solid var(--line)}"
"th{color:var(--dim);font-weight:500;font-size:11px;text-transform:uppercase;"
"letter-spacing:.7px}"
"td{font-family:var(--mono);font-size:12px}"
"</style>"
"</head>"
"<body>"
"<div class='wrap'>"

"<header>"
"<div class='logo'><svg viewBox='0 0 24 24'><path d='M8 5.5v13l11-6.5z'/></svg></div>"
"<div>"
"<h1>camstream</h1>"
"<div class='sub' id='subline'>low latency WebRTC camera server</div>"
"</div>"
"<div style='flex:1'></div>"
"<span class='pill' id='modePill'>idle</span>"
"<span class='pill' id='verPill'>v?</span>"
"</header>"

"<div class='grid'>"
"<div class='stack'>"

"<div class='card'>"
"<h2><span class='dot' style='color:var(--red);display:none' id='liveDot'></span>"
"live video</h2>"
"<div class='stage'>"
"<video id='vid' autoplay playsinline muted></video>"
"<div class='idle' id='idle'>"
"<div><div class='big'>📷</div>"
"<div>Press <b>Start WebRTC</b> to connect.<br>"
"The media path uses ICE, DTLS and SRTP over UDP.</div></div>"
"</div>"
"<div class='overlay'>"
"<span class='tag' id='tagRes'>no signal</span>"
"<span class='tag' id='tagRtt'>rtt -</span>"
"</div>"
"</div>"
"<div class='controls'>"
"<button class='primary' id='btnStart'>Start WebRTC</button>"
"<button class='danger' id='btnStop' disabled>Stop</button>"
"<button class='ghost' id='btnShot' disabled>Snapshot</button>"
"<button class='ghost' id='btnFull'>Fullscreen</button>"
"</div>"
"<div class='hint' id='hint'></div>"
"</div>"

"<div class='card'>"
"<h2>server</h2>"
"<div id='serverInfo'><div class='rowline'><span class='k'>loading</span>"
"<span class='v'>...</span></div></div>"
"</div>"

"<div class='card'>"
"<h2>event log</h2>"
"<div class='log' id='log'></div>"
"</div>"

"</div>"
"<div class='stack'>"

"<div class='card'>"
"<h2>connection timeline</h2>"
"<div class='steps'>"
"<div class='step' id='stHttp'><span class='ic'>1</span>HTTP page and signaling</div>"
"<div class='step' id='stSig'><span class='ic'>2</span>SDP offer and answer</div>"
"<div class='step' id='stIce'><span class='ic'>3</span>ICE connectivity check</div>"
"<div class='step' id='stDtls'><span class='ic'>4</span>DTLS 1.2 handshake</div>"
"<div class='step' id='stSrtp'><span class='ic'>5</span>SRTP keys derived</div>"
"<div class='step' id='stMedia'><span class='ic'>6</span>video streaming</div>"
"</div>"
"</div>"

"<div class='card'>"
"<h2>receiver statistics</h2>"
"<div class='stats'>"
"<div class='stat'><div class='v' id='sBit'>0.0</div><div class='l'>Mbps</div>"
"<canvas class='spark' id='spBit' width='300' height='34'></canvas></div>"
"<div class='stat'><div class='v' id='sFps'>0</div><div class='l'>FPS</div>"
"<canvas class='spark' id='spFps' width='300' height='34'></canvas></div>"
"<div class='stat'><div class='v' id='sRtt'>-</div><div class='l'>RTT ms</div></div>"
"<div class='stat'><div class='v' id='sJit'>-</div><div class='l'>jitter ms</div></div>"
"<div class='stat'><div class='v' id='sLost'>0</div><div class='l'>packets lost</div></div>"
"<div class='stat'><div class='v' id='sDec'>0</div><div class='l'>frames decoded</div></div>"
"</div>"
"</div>"

"<div class='card'>"
"<h2>viewers</h2>"
"<table><thead><tr><th>id</th><th>state</th><th>pkts</th><th>pli</th></tr></thead>"
"<tbody id='sessBody'><tr><td colspan='4'>none</td></tr></tbody></table>"
"</div>"

"</div>"
"</div>"

"<footer>"
"Video path: H.264 over RTP, protected with DTLS 1.2 and SRTP, media on UDP "
"(WebRTC is the only transport; HTTP is used for the page and signaling only).<br>"
"If media does not connect while the page loads, the browser probably cannot reach "
"the UDP port (NAT, proxy or firewall). Open this page directly on the LAN and allow "
"the UDP port range in the firewall. See the LAN setup guide in the repository docs."
"</footer>"

"</div>"

"<script>"
"var vid=document.getElementById('vid');"
"var log=document.getElementById('log');"
"var hint=document.getElementById('hint');"
"var pc=null,sessionId=0,statsTimer=null,monitorTimer=null;"
"var lastBytes=0,lastDecoded=0,lastLost=0,lastTime=0;"
"var bitHist=[],fpsHist=[];"

"function tstamp(){var d=new Date();"
"return d.toTimeString().slice(0,8)}"
"function addLog(msg,cls){var e=document.createElement('div');"
"e.className=cls||'';"
"e.innerHTML='<span class=t>'+tstamp()+'</span>'+msg;"
"log.prepend(e);"
"while(log.children.length>200)log.lastChild.remove()}"

"function setStep(id,state){"
"var e=document.getElementById(id);"
"e.className='step'+(state?' '+state:'')}"

"function allIdle(){['stSig','stIce','stDtls','stSrtp','stMedia'].forEach("
"function(s){setStep(s,'')})}"

"function setMode(t,ok){var p=document.getElementById('modePill');"
"p.textContent=t;p.className='pill'+(ok?' ok':'')}"

"function showHint(html){hint.innerHTML=html;hint.classList.add('show')}"
"function hideHint(){hint.classList.remove('show')}"

"function spark(id,data,max){"
"var c=document.getElementById(id);var g=c.getContext('2d');"
"g.clearRect(0,0,c.width,c.height);"
"if(data.length<2)return;"
"var step=c.width/(59);"
"g.beginPath();"
"for(var i=0;i<data.length;i++){"
"var x=c.width-(data.length-1-i)*step;"
"var y=c.height-3-(data[i]/max)*(c.height-6);"
"if(i===0)g.moveTo(x,y);else g.lineTo(x,y)}"
"g.strokeStyle='#60a5fa';g.lineWidth=2;g.stroke();"
"g.lineTo(c.width,c.height);g.lineTo(c.width-(data.length-1)*step,c.height);"
"g.closePath();g.fillStyle='rgba(96,165,250,0.18)';g.fill()}"

/* ---------------- WebRTC ---------------- */

"async function connectRtc(){"
"if(pc)return;"
"try{"
"hideHint();allIdle();"
"setStep('stHttp','ok');"
"pc=new RTCPeerConnection({iceServers:[]});"
"pc.addTransceiver('video',{direction:'recvonly'});"
"pc.ontrack=function(ev){vid.srcObject=ev.streams[0];"
"addLog('remote track received','ok')};"
"pc.oniceconnectionstatechange=function(){"
"var s=pc?pc.iceConnectionState:'closed';"
"addLog('ICE state: '+s);"
"if(s==='checking')setStep('stIce','active');"
"if(s==='connected'||s==='completed'){setStep('stIce','ok');setStep('stDtls','ok')}"
"if(s==='failed'){setStep('stIce','fail');"
"showHint('ICE failed: the browser could not send UDP to the server. "
"When this page is opened through a proxy, media cannot traverse. "
"Open it directly via the LAN IP and check the firewall for the UDP port range.')}};"
"pc.onconnectionstatechange=function(){"
"var s=pc?pc.connectionState:'closed';"
"if(s==='connecting')setStep('stDtls','active');"
"if(s==='connected'){setStep('stDtls','ok');setStep('stSrtp','ok')}};"
"var offer=await pc.createOffer();"
"await pc.setLocalDescription(offer);"
"setStep('stSig','active');"
"addLog('sending SDP offer');"
"var r=await fetch('/rtc/offer',{method:'POST',"
"headers:{'Content-Type':'application/json'},"
"body:JSON.stringify({type:'offer',sdp:offer.sdp})});"
"if(!r.ok){var t=await r.text();throw new Error('signaling failed: '+t)}"
"var answer=await r.json();"
"sessionId=answer.session_id;"
"await pc.setRemoteDescription({type:'answer',sdp:answer.sdp});"
"setStep('stSig','ok');"
"addLog('SDP answer applied, session '+sessionId,'ok');"
"setMode('webrtc',true);"
"document.getElementById('btnStart').disabled=true;"
"document.getElementById('btnStop').disabled=false;"
"document.getElementById('btnShot').disabled=false;"
"document.getElementById('idle').style.display='none';"
"startStats()"
"}catch(err){"
"addLog(String(err),'err');"
"setStep('stSig','fail');"
"cleanupRtc()"
"}}"

"function cleanupRtc(){"
"if(statsTimer){clearInterval(statsTimer);statsTimer=null}"
"if(monitorTimer){clearTimeout(monitorTimer);monitorTimer=null}"
"if(pc){pc.close();pc=null}}"

"function stopRtc(){"
"if(sessionId){"
"fetch('/rtc/close',{method:'POST',headers:{'Content-Type':'application/json'},"
"body:JSON.stringify({session_id:sessionId})}).catch(function(){});"
"sessionId=0}"
"cleanupRtc();"
"vid.srcObject=null;"
"document.getElementById('idle').style.display='grid';"
"document.getElementById('btnStart').disabled=false;"
"document.getElementById('btnStop').disabled=true;"
"document.getElementById('btnShot').disabled=true;"
"allIdle();setStep('stHttp','ok');"
"setMode('idle',false);"
"addLog('disconnected')}"

"function startStats(){"
"lastBytes=0;lastDecoded=0;lastLost=0;lastTime=performance.now();"
"bitHist=[];fpsHist=[];"
"statsTimer=setInterval(pollStats,1000);"
"monitorTimer=setTimeout(checkFirstFrame,9000)}"

"async function pollStats(){"
"if(!pc)return;"
"var res=await pc.getStats();"
"var v=null,pair=null;"
"res.forEach(function(s){"
"if(s.type==='inbound-rtp'){if(s.kind==='video'||s.isRemote===undefined)v=s}"
"if(s.type==='candidate-pair'&&s.state==='succeeded'&&"
"(s.nominated||s.selected===true))pair=s});"
"if(!v)return;"
"var now=performance.now();"
"var dt=(now-lastTime)/1000;"
"if(v.bytesReceived!=null){"
"var mbps=(v.bytesReceived-lastBytes)*8/dt/1000000;"
"lastBytes=v.bytesReceived;"
"bitHist.push(mbps);if(bitHist.length>60)bitHist.shift();"
"document.getElementById('sBit').textContent=mbps.toFixed(2);"
"spark('spBit',bitHist,Math.max(1,Math.max.apply(null,bitHist)))}"
"var fps=v.framesPerSecond;"
"if(fps==null&&dt>0){fps=(v.framesDecoded-lastDecoded)/dt;fps=Math.round(fps)}"
"lastDecoded=v.framesDecoded||0;"
"if(fps!=null){fpsHist.push(fps);if(fpsHist.length>60)fpsHist.shift();"
"document.getElementById('sFps').textContent=fps;"
"spark('spFps',fpsHist,Math.max(30,Math.max.apply(null,fpsHist)))}"
"if(v.jitter!=null)document.getElementById('sJit').textContent="
"(v.jitter*1000).toFixed(1);"
"if(v.packetsLost!=null){document.getElementById('sLost').textContent=v.packetsLost}"
"document.getElementById('sDec').textContent=v.framesDecoded||0;"
"if(v.frameWidth)document.getElementById('tagRes').textContent="
"v.frameWidth+'x'+v.frameHeight;"
"if(pair&&pair.currentRoundTripTime!=null){"
"var rtt=Math.round(pair.currentRoundTripTime*1000);"
"document.getElementById('sRtt').textContent=rtt;"
"document.getElementById('tagRtt').textContent='rtt '+rtt+' ms'}"
"if((v.framesDecoded||0)>0){setStep('stMedia','ok');"
"document.getElementById('liveDot').style.display='inline-block';"
"document.getElementById('idle').style.display='none'}"
"lastTime=now}"

"function checkFirstFrame(){"
"if(pc&&document.getElementById('stMedia').className.indexOf('ok')<0){"
"addLog('no video within 9s, see hint','warn');"
"showHint('Signaling succeeded but no video arrived. Likely causes: "
"UDP media blocked by firewall (open the UDP port range), or this page was "
"opened through a reverse proxy that cannot forward UDP.')}}"

/* ---------------- actions ---------------- */

"document.getElementById('btnStart').onclick=connectRtc;"
"document.getElementById('btnStop').onclick=stopRtc;"
"document.getElementById('btnFull').onclick=function(){"
"var st=document.querySelector('.stage');"
"if(document.fullscreenElement)document.exitFullscreen();"
"else if(st.requestFullscreen)st.requestFullscreen()};"
"document.getElementById('btnShot').onclick=function(){"
"var s=document.createElement('canvas');"
"var w=vid.videoWidth||640;"
"var h=vid.videoHeight||480;"
"s.width=w;s.height=h;"
"s.getContext('2d').drawImage(vid,0,0,w,h);"
"var a=document.createElement('a');"
"a.download='snapshot-'+Date.now()+'.png';a.href=s.toDataURL('image/png');a.click();"
"addLog('snapshot saved','ok')};"

/* ---------------- server info ---------------- */

"function pollStatus(){"
"fetch('/status').then(function(r){return r.json()}).then(function(j){"
"document.getElementById('verPill').textContent='v'+j.version;"
"var src=j.source,enc=j.encoder;"
"var html='';"
"html+=\"<div class='rowline'><span class='k'>source</span><span class='v'>\""
"+src.name+\" (\"+src.width+'x'+src.height+' @ '+src.fps+\")</span></div>\";"
"html+=\"<div class='rowline'><span class='k'>encoder</span><span class='v'>\""
"+enc.name+\"</span></div>\";"
"html+=\"<div class='rowline'><span class='k'>bitrate target</span>\""
"+\"<span class='v'>\"+enc.bitrate_kbps+' kbps, IDR every '+enc.keyframe_seconds"
"+\"s</span></div>\";"
"html+=\"<div class='rowline'><span class='k'>captured frames</span>\""
"+\"<span class='v'>\"+j.captured_frames+\"</span></div>\";"
"html+=\"<div class='rowline'><span class='k'>encoded frames</span>\""
"+\"<span class='v'>\"+j.encoded_frames+\"</span></div>\";"
"var ips='';"
"j.interfaces.forEach(function(f){"
"ips+=\"<div class='rowline'><span class='k'>\"+f.name+\"</span>\""
"+\"<span class='v'><a class='ip' href='http://\"+f.ip+':'+j.http_port"
"+\"/'>\"+f.ip+':'+j.http_port+\"</a></span></div>\"});"
"if(ips)html+=ips;"
"document.getElementById('serverInfo').innerHTML=html;"
"var body=document.getElementById('sessBody');"
"if(!j.sessions.length){body.innerHTML='<tr><td colspan=4>none</td></tr>'}"
"else{var rows='';"
"j.sessions.forEach(function(s){"
"rows+=\"<tr><td>\"+(''+s.id).padStart(8,'0')+\"</td><td>\"+s.state"
"+\"</td><td>\"+s.packets_sent+\"</td><td>\"+s.pli+\"</td></tr>\"});"
"body.innerHTML=rows}"
"}).catch(function(){})}"

"pollStatus();"
"setInterval(pollStatus,1500);"
"setStep('stHttp','ok');"
"addLog('interface ready, WebRTC transport available');"
"</script>"
"</body>"
"</html>";
